name: ci-wf
on:
  push:
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: welcome steps
        run: echo "welcome from the git hub actions"
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: repoitor Info
        run: |
         echo "Follwing is the informnation about the cloned Repo"
         echo "Repository Name :${{github.repository}}"
         echo "Repository Owner :${{github.owner}}"
         git branch
         git log
         git config --local --list